# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 468)
        
        script_dir = os.path.dirname(os.path.abspath(__file__))

        #设置背景图片
        palette = QtGui.QPalette()
        background_image = QtGui.QPixmap(os.path.join(script_dir, 'pics/background.png'))  # 指定背景图片路径
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(background_image))
        Form.setPalette(palette)

        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 501, 411))
        self.groupBox.setObjectName("groupBox")

        self.weatherComboBox = QtWidgets.QComboBox(self.groupBox)
        self.weatherComboBox.setGeometry(QtCore.QRect(60, 20, 131, 31))
        self.weatherComboBox.setObjectName("weatherComboBox")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")

        self.dateComboBox = QtWidgets.QComboBox(self.groupBox)
        self.dateComboBox.setGeometry(QtCore.QRect(120, 20, 131, 31))
        self.dateComboBox.setObjectName("dateComboBox")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")

        # 修改标签的字体以加粗
        font = QtGui.QFont()
        font.setBold(True)

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 31))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 301, 301))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.icon_humid = QtWidgets.QLabel(self.groupBox_2)
        self.icon_humid.setGeometry(QtCore.QRect(40, 230, 21, 21))
        self.icon_humid.setObjectName("icon_humid")
        self.label_time = QtWidgets.QLabel(self.groupBox_2)
        # self.label_time.setFrameShape(QtWidgets.QFrame.Box)
        self.label_time.setGeometry(QtCore.QRect(0, 20, 301, 20))
        self.label_time.setObjectName("label_time")
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_time.setFont(font)  # 设置修改后的字体
        self.low = QtWidgets.QLabel(self.groupBox_2)
        self.low.setGeometry(QtCore.QRect(170, 140, 120, 51))
        self.low.setLineWidth(1)
        self.low.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.low.setObjectName("low")
        self.temperature = QtWidgets.QLabel(self.groupBox_2)
        self.temperature.setGeometry(QtCore.QRect(40, 40, 100, 160))
        self.temperature.setObjectName("temperature")
        self.temperature.setFont(font)  # 设置修改后的字体
        self.label_humid = QtWidgets.QLabel(self.groupBox_2)
        self.label_humid.setGeometry(QtCore.QRect(70, 230, 100, 21))
        self.label_humid.setObjectName("label_humid")
        self.label_humid.setFont(font)  # 设置修改后的字体
        self.icon_wind = QtWidgets.QLabel(self.groupBox_2)
        self.icon_wind.setGeometry(QtCore.QRect(170, 230, 21, 21))
        self.icon_wind.setObjectName("icon_wind")
        self.label_wind = QtWidgets.QLabel(self.groupBox_2)
        self.label_wind.setGeometry(QtCore.QRect(200, 230, 100, 21))
        self.label_wind.setObjectName("label_wind")
        self.label_wind.setFont(font)  # 设置修改后的字体
        self.icon_pm = QtWidgets.QLabel(self.groupBox_2)
        self.icon_pm.setGeometry(QtCore.QRect(40, 260, 21, 21))
        self.icon_pm.setObjectName("icon_pm")
        self.label_pm = QtWidgets.QLabel(self.groupBox_2)
        self.label_pm.setGeometry(QtCore.QRect(70, 260, 100, 21))
        self.label_pm.setObjectName("label_pm")
        self.label_pm.setFont(font)  # 设置修改后的字体
        self.label_quality = QtWidgets.QLabel(self.groupBox_2)
        self.label_quality.setGeometry(QtCore.QRect(200, 260, 91, 21))
        self.label_quality.setObjectName("label_quality")
        self.label_quality.setFont(font)  # 设置修改后的字体
        self.icon_quality = QtWidgets.QLabel(self.groupBox_2)
        self.icon_quality.setGeometry(QtCore.QRect(170, 260, 21, 21))
        self.icon_quality.setObjectName("icon_quality")
        self.high = QtWidgets.QLabel(self.groupBox_2)
        self.high.setGeometry(QtCore.QRect(170, 50, 120, 51))
        self.high.setLineWidth(1)
        self.high.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.high.setObjectName("high")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(329, 60, 161, 301))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.date = QtWidgets.QLabel(self.groupBox_3)
        self.date.setGeometry(QtCore.QRect(10, 20, 141, 20))
        # self.date.setFrameShape(QtWidgets.QFrame.Box)
        self.date.setMidLineWidth(0)
        self.date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date.setObjectName("date")
        self.date.setFont(font)  # 设置修改后的字体
        self.weatherIconLabel = QtWidgets.QLabel(self.groupBox_3)
        self.weatherIconLabel.setGeometry(QtCore.QRect(35, 100, 100, 100))
        self.weatherIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weatherIconLabel.setObjectName("weatherIconLabel")
        self.label_sunrise = QtWidgets.QLabel(self.groupBox_3)
        self.label_sunrise.setGeometry(QtCore.QRect(53, 230, 100, 20))
        self.label_sunrise.setObjectName("label_sunrise")
        self.label_sunrise.setFont(font)  # 设置修改后的字体
        self.icon_sunrise = QtWidgets.QLabel(self.groupBox_3)
        self.icon_sunrise.setGeometry(QtCore.QRect(20, 230, 21, 21))
        self.icon_sunrise.setObjectName("icon_sunrise")
        self.label_sunset = QtWidgets.QLabel(self.groupBox_3)
        self.label_sunset.setGeometry(QtCore.QRect(53, 260, 100, 20))
        self.label_sunset.setObjectName("label_sunset")
        self.label_sunset.setFont(font)  # 设置修改后的字体
        self.icon_sunset = QtWidgets.QLabel(self.groupBox_3)
        self.icon_sunset.setGeometry(QtCore.QRect(20, 260, 21, 21))
        self.icon_sunset.setObjectName("icon_sunset")
        self.weather = QtWidgets.QLabel(self.groupBox_3)
        self.weather.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.weather.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather.setObjectName("weather")
        self.weather.setFont(font)  # 设置修改后的字体
        self.text_notice = QtWidgets.QLabel(self.groupBox)
        self.text_notice.setGeometry(QtCore.QRect(30, 369, 441, 31))
        self.text_notice.setObjectName("text_notice")
        self.text_notice.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)

        # 设置文本样式表，包括字体大小和样式
        self.text_notice.setStyleSheet("font-size: 20px; font-weight: bold;")  # 根据需要调整字体大小和样式
        
        self.saveBtn = QtWidgets.QPushButton(Form)
        self.saveBtn.setGeometry(QtCore.QRect(76, 430, 93, 28))
        self.saveBtn.setObjectName("saveButton")
        self.queryBtn = QtWidgets.QPushButton(Form)
        self.queryBtn.setGeometry(QtCore.QRect(216, 430, 93, 28))
        self.queryBtn.setObjectName("queryBtn")
        self.clearBtn = QtWidgets.QPushButton(Form)
        self.clearBtn.setGeometry(QtCore.QRect(356, 430, 93, 28))
        self.clearBtn.setObjectName("clearBtn")
        
        # 创建按钮
        self.weatherBtn = QtWidgets.QPushButton(Form)
        self.weatherBtn.setGeometry(QtCore.QRect(280, 20, 93, 50))
        self.weatherBtn.setObjectName("weatherButton")

        # 设置按钮的样式表
        self.weatherBtn.setStyleSheet("background-color: transparent; border: none;")

        # 设置按钮的图标
        icon = QtGui.QIcon(os.path.join(script_dir, 'pics/icon_open.png'))  # 替换为您的图标文件路径
        self.weatherBtn.setIcon(icon)
        self.weatherBtn.setIconSize(QtCore.QSize(93, 50))  # 设置图标的大小

        # 连接按钮的点击事件
        self.weatherBtn.clicked.connect(Form.openWeatherWebsite)

        self.retranslateUi(Form)
        self.clearBtn.clicked.connect(Form.clearResult) 
        # self.queryBtn.clicked.connect(Form.queryWeather) 
        self.queryBtn.clicked.connect(Form.on_dateComboBox_activated)
        self.saveBtn.clicked.connect(Form.saveWeatherInfo)
        QtCore.QMetaObject.connectSlotsByName(Form)    


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "czx的天气查询"))
        self.groupBox.setTitle(_translate("Form", "查询城市天气"))
        self.label.setText(_translate("Form", "城市"))
        self.queryBtn.setText(_translate("Form", "查询"))
        self.clearBtn.setText(_translate("Form", "清空"))
        self.saveBtn.setText(_translate("Form", "保存"))

    def populate_city_names(self, city_names):
        self.weatherComboBox.clear()
        self.weatherComboBox.addItems(city_names)

    def display_weather_icon(self, weather_type):
        # 在这里根据天气类型显示对应的天气图标
        script_dir = os.path.dirname(os.path.abspath(__file__))

        if weather_type == "晴":
            weather_icon = QtGui.QPixmap(os.path.join(script_dir, 'pics/sunny_icon.png'))  # 指定晴天图标路径
        elif weather_type == "多云" or weather_type == "阴":
            weather_icon = QtGui.QPixmap(os.path.join(script_dir, 'pics/cloudy_icon.png')) # 指定多云图标路径
        elif weather_type == "霾":
            weather_icon = QtGui.QPixmap(os.path.join(script_dir, 'pics/haze_icon.png'))  # 指定雾霾图标路径
        elif weather_type == "小雨" or weather_type == "中雨":
            weather_icon = QtGui.QPixmap(os.path.join(script_dir, 'pics/rainy_icon.png'))  # 指定小雨图标路径
        elif weather_type == "大雨":
            weather_icon = QtGui.QPixmap(os.path.join(script_dir, 'pics/bigrain_icon.png'))  # 指定大雨图标路径
        # 更新 QLabel 的图像
        self.weatherIconLabel.setPixmap(weather_icon)
        self.weatherIconLabel.setScaledContents(True)

        self.temperature.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/temperature.png')))
        self.temperature.setScaledContents(True)
        self.icon_humid.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/icon_humid.png')))
        self.icon_humid.setScaledContents(True)
        self.icon_wind.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/icon_wind.png')))
        self.icon_wind.setScaledContents(True)
        self.icon_quality.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/icon_quality.png')))
        self.icon_quality.setScaledContents(True)
        self.icon_pm.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/icon_pm.png')))
        self.icon_pm.setScaledContents(True)
        self.icon_sunrise.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/icon_sunrise.png')))
        self.icon_sunrise.setScaledContents(True)
        self.icon_sunset.setPixmap(QtGui.QPixmap(os.path.join(script_dir, 'pics/icon_sunset.png')))
        self.icon_sunset.setScaledContents(True)

        self.date,self.high,self.weather
